name: education_system
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  image_cropper:
  universal_html:
  restart_app:
  image_picker:
  image_picker_web:
  cached_network_image:
  chewie:
  video_player:
  fluttertoast: ^8.2.4
  intl:
  carousel_indicator:
  carousel_slider:
  flutter_bloc:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  firebase_core:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
